# Generated by Django 2.1 on 2021-11-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipt_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='account_user',
            field=models.IntegerField(verbose_name='Account User'),
        ),
    ]
