# Generated by Django 2.1 on 2021-12-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_auto_20211130_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file_name', models.CharField(max_length=64, verbose_name='Upload File Name')),
                ('account_user', models.IntegerField(verbose_name='Account User')),
                ('file_name', models.CharField(max_length=64, verbose_name='File Name')),
            ],
        ),
    ]
